# 项目相关配置
xingcloud:
  # 名称
  name: testModule
  # 版本
  version: 1.0-SNAPSHOT
  # 版权年份
  copyrightYear: 2020
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/xingcloud/uploadPath，Linux配置 /home/xingcloud/uploadPath）
  profile: /home/xingcloud/uploadPath
  # 获取ip地址开关
  addressEnabled: true
# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 80
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    basedir: /tmp
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30


## 日志配置
#logging:
#  level:
#    com.xingcloud: debug
#    org.springframework: warn

# Spring配置
spring:
  aop:
    auto: true
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  10MB
      # 设置总上传的文件大小
      max-request-size:  20MB
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  #    prefix: classpath:/templates
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: ibms
    #    host: localhost
    port: 6379
    password: 123456
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# token配置
#token:
#  # 令牌自定义标识
#  header: Authorization
#  # 令牌秘钥
#  secret: abcdefghijklmnopqrstuvwxyz
#  # 令牌有效期（默认30分钟）
#  expireTime: 320

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.cc1500
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#
## Swagger配置
swagger:
  enable: true
#
## 防止XSS攻击
#xss:
#  # 过滤开关
#  enabled: true
#  # 排除链接（多个用逗号分隔）
#  excludes: /system/notice/*
#  # 匹配链接
#  urlPatterns: /system/*,/monitor/*,/tool/*

## 代码生成
#gen:
#  # 作者
#  author: xingcloud
#  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool
#  packageName: com.xingcloud.project.system
#  # 自动去除表前缀，默认是true
#  autoRemovePre: false
#  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）
#  tablePrefix: sys_
##二维码访问公司域名设置
#companyName: http://ibms.xingzhoukeji.com
##会议发布终端服务器配置
#meetrRelease:
#  token: 123456
#  method: sendProgram
#  service: send
#closeLight:
#  minute: 1
# video:
#   websocket: http://192.168.216.97:8081/
#   secret: video
#邮件服务器配置
#mail:
#  #设置邮件发送的服务器，这里为QQ邮件服务器
#  host: smtp.qq.com
#  #设置发件人
#  from: 654502383@qq.com
#  #授权码
#  password: uznpkwijykanbdjj
#face:
#  API_KEY: gi9E7Wgh5IKl7RZnUj7KUu2a
#  SECRET_KEY: y7pO1vDKxfsjsv2KQ3rmGDwH0BlRo602
#  API_ID: 18516607
#  AUTH_HOST: https://aip.baidubce.com/oauth/2.0/token?